package gateway

import "time"

type Decision string

const (
	Allow           Decision = "ALLOW"
	Redact          Decision = "REDACT"
	Throttle        Decision = "THROTTLE"
	Ghost           Decision = "GHOST"
	RequireApproval Decision = "REQUIRE_APPROVAL"
	Block           Decision = "BLOCK"
)

type Principal struct {
	ID          string   `json:"id"`
	Role        string   `json:"role,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

type Agent struct {
	ID          string   `json:"id"`
	Model       string   `json:"model,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

type Usage struct {
	Tokens    int     `json:"tokens"`
	CostUSD   float64 `json:"cost_usd"`
	ToolCalls int     `json:"tool_calls"`
	Steps     int     `json:"steps"`
	RuntimeMS int     `json:"runtime_ms"`
}

type EvaluateRequest struct {
	RequestID      string            `json:"request_id,omitempty"`
	SessionID      string            `json:"session_id,omitempty"`
	User           Principal         `json:"user"`
	Agent          Agent             `json:"agent"`
	Action         string            `json:"action"`
	Resource       string            `json:"resource"`
	Prompt         string            `json:"prompt"`
	OriginalIntent string            `json:"original_intent,omitempty"`
	Usage          Usage             `json:"usage"`
	Metadata       map[string]string `json:"metadata,omitempty"`
	// Messages carries an OpenAI-style conversation for llm.generate.
	Messages []ChatMessage `json:"-"`
	// DryRun marks verdict-only evaluation: no step is counted, no session is
	// created and no executable approval is opened.
	DryRun bool `json:"-"`
}

type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type SemanticScores struct {
	PromptInjection  float64  `json:"prompt_injection"`
	DataExfiltration float64  `json:"data_exfiltration"`
	IntentAlignment  float64  `json:"intent_alignment"`
	PrivilegeDrift   float64  `json:"privilege_drift"`
	MemoryPoisoning  float64  `json:"memory_poisoning"`
	Risk             float64  `json:"risk"`
	Signals          []string `json:"signals,omitempty"`
}

type Timings struct {
	TotalMS         float64 `json:"total_ms"`
	GatewayMS       float64 `json:"gateway_ms"`
	DeterministicMS float64 `json:"deterministic_ms"`
	SemanticMS      float64 `json:"semantic_ms"`
}

type GhostSession struct {
	ID              string   `json:"id"`
	ReadOnly        bool     `json:"read_only"`
	NetworkDisabled bool     `json:"network_disabled"`
	Credentials     bool     `json:"credentials_available"`
	AllowedTools    []string `json:"allowed_tools"`
	ExpiresAt       string   `json:"expires_at"`
}

type EvaluateResponse struct {
	RequestID            string         `json:"request_id"`
	SessionID            string         `json:"session_id"`
	Decision             Decision       `json:"decision"`
	Reasons              []string       `json:"reasons"`
	Risk                 float64        `json:"risk"`
	RedactedPrompt       string         `json:"redacted_prompt,omitempty"`
	EffectivePermissions []string       `json:"effective_permissions"`
	Semantic             SemanticScores `json:"semantic"`
	SemanticEscalated    bool           `json:"semantic_escalated"`
	PolicyVersion        string         `json:"policy_version"`
	PolicyReloadedAt     string         `json:"policy_reloaded_at"`
	GhostSession         *GhostSession  `json:"ghost_session,omitempty"`
	ApprovalID           string         `json:"approval_id,omitempty"`
	Timings              Timings        `json:"timings"`
	Explanation          Explanation    `json:"explanation"`
	Warnings             []string       `json:"warnings,omitempty"`
	Trace                []TraceStep    `json:"trace,omitempty"`
	DetailsHidden        bool           `json:"details_hidden,omitempty"`

	scopes   []BudgetScope
	reserved Usage
}

// Explanation is generated by the local Python/Ollama explainer. Go only
// transports and sanitizes it; it never creates explanatory prose.
type Explanation struct {
	Status   string   `json:"status"`
	Model    string   `json:"model,omitempty"`
	Title    string   `json:"title"`
	Summary  string   `json:"summary"`
	Factors  []string `json:"factors"`
	NextStep string   `json:"next_step"`
}

type AuditEvent struct {
	ID                string         `json:"id"`
	Timestamp         string         `json:"timestamp"`
	User              string         `json:"user"`
	Role              string         `json:"role"`
	Agent             string         `json:"agent"`
	Model             string         `json:"model,omitempty"`
	Action            string         `json:"action"`
	Resource          string         `json:"resource"`
	Decision          Decision       `json:"decision"`
	Reasons           []string       `json:"reasons"`
	Controls          []string       `json:"controls"`
	PolicyVersion     string         `json:"policy_version"`
	Risk              float64        `json:"risk"`
	Semantic          SemanticScores `json:"semantic"`
	Tokens            int            `json:"tokens"`
	CostUSD           float64        `json:"cost_usd"`
	LatencyMS         float64        `json:"latency_ms"`
	GatewayMS         float64        `json:"gateway_ms"`
	DeterministicMS   float64        `json:"deterministic_ms"`
	SemanticMS        float64        `json:"semantic_ms"`
	SemanticEscalated bool           `json:"semantic_escalated"`
	SessionID         string         `json:"session_id,omitempty"`
	ExecutionStatus   string         `json:"execution_status,omitempty"`
	ActualTokens      int            `json:"actual_tokens,omitempty"`
	ApprovedBy        string         `json:"approved_by,omitempty"`
	Explanation       Explanation    `json:"explanation"`
	Trace             []TraceStep    `json:"trace,omitempty"`
	DetailsHidden     bool           `json:"details_hidden,omitempty"`
}

// TraceStep is one check of the decision pipeline, shown in the event drawer.
// Result is pass, flag (acted but not decisive), fail (decisive) or skip.
type TraceStep struct {
	Check     string   `json:"check"`
	Result    string   `json:"result"`
	Detail    string   `json:"detail,omitempty"`
	Score     *float64 `json:"score,omitempty"`
	Threshold *float64 `json:"threshold,omitempty"`
}

type SessionState struct {
	Key            string
	OriginalIntent string
	Registered     bool
	Steps          int
	History        []string
	Sensitivity    []float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	// Principal* hold the user+agent history across sessions inside the
	// drift window, so rotating session ids does not reset Privilege Drift.
	PrincipalHistory     []string
	PrincipalSensitivity []float64
}
